AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 145

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
