AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 145
