name: Allowed Dependency Licensing
on: [push]

jobs:
  LicenseFinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1

      - name: Check Allowed Licenses
        run: |
          bundle install
          bundle lock --add-platform x86_64-linux
          bundle exec license_finder permitted_licenses add "MIT" "Brakeman Public Use License" "GPL-3.0+" "Apache 2.0" "Simplified BSD" "New BSD"
          bundle exec license_finder
