name: Dependency Vulnerabilities
on: [push]

jobs:
  BundlerAudit:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Verify Bundler
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit check
