name: Static Analysis Security Vulnerabilities
on: [push]

jobs:
  Brakeman:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1

      - name: Check Security Vulnerabilities
        run: |
          bundle lock --add-platform x86_64-linux
          bundle exec brakeman
